<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DanmuApi.Runtime\DanmuApi.Runtime.csproj" />
    <ProjectReference Include="..\DanmuApi.Core\DanmuApi.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\kotlin-preview-1.sha256" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
